WebUI/Controllers/CourseController.cs
using Business.Abstract;
using Business.Concrete;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class CourseController : Controller
    {
        IIdentityService _ıdentityService;
        ICourseService _courseService;

        public CourseController(ICourseService courseService, IIdentityService ıdentityService)
        {
            _courseService = courseService;
            _ıdentityService = ıdentityService;
        }

        // GET: Course
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IndexQuery(string tcNo)
        {
            var result = _ıdentityService.GetPersonDetails(tcNo).Data;
            return View(result);
        }

        public ActionResult CourseGetList(int id)
        {
            ViewBag.PersonelKimlikId = id;
            var courseGetList = _courseService.GetAllByIdentityId(id).Data;
            return View("CourseGetList", courseGetList);
        }

        public ActionResult CourseGet(int id)
        {
            var courseGet = _courseService.GetById(id).Data;
            return View("CourseGet", courseGet);
        }


        [HttpGet]
        public ActionResult CourseUpdate()
        {
            return View();
        }


        [HttpPost]
        public ActionResult CourseUpdate(Course course)

        {
            _courseService.Update(course);
            return RedirectToAction("");
        }

        [HttpGet]
        public ActionResult CourseAdd(int id)
        {
            var courseAdd = _courseService.GetById(id).Data;
            ViewBag.PersonelKimlikId = id;
            return View("CourseAdd", courseAdd);
        }


        [HttpPost]
        public ActionResult CourseAdd(Course course)
        {
            _courseService.Add(course);
            return RedirectToAction("");
        }
    }
}

WebUI/Views/Course/CourseAdd.cshtml
@using Entities.Concrete
@model Course
@{
    ViewBag.Title = "CourseAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Kurs Bilgisi Ekle</h3>
@using (Html.BeginForm("CourseAdd", "Course", FormMethod.Post))
{
    <div class="box box-primary">
        <div class="box-header with-border">
            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                <thead>

                </thead>
                <tbody>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><b>Türü</b></td>
                        <td>
                            @Html.Hidden("PersonelKimlikId", (int)ViewBag.PersonelKimlikId)
                            @Html.HiddenFor(x => x.PersonelKursId)
                            @Html.TextBoxFor(x => x.Turu, null, new { @class = "form-control" })
                        </td>
                        <td><b>Şekli</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.Sekli, null, new { @class = "form-control" })
                        </td>
                        <td><b>Konusu</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.Konusu, null, new { @class = "form-control" })
                        </td>
                    </tr>
                    <tr>
                        <td><b>Kurs Sınav Adı</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.KursSinavAdi, null, new { @class = "form-control" })
                        </td>
                        <td><b>Başlangıç Tarihi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.BaslamaTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "Date" })
                        </td>
                        <td><b>Bitiş Tarihi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.BitisTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "Date" })
                        </td>

                    </tr>
            </table>
            <button class="btn btn-success">Ekle</button>
        </div>
    </div>
}

WebUI/Views/Course/CourseGet.cshtml
@using Entities.Concrete
@model Course
@{
    ViewBag.Title = "CourseGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Kurs Bilgisi Güncelle</h3>
@using (Html.BeginForm("CourseUpdate", "Course", FormMethod.Post))
{
    <div class="box box-primary">
        <div class="box-header with-border">
            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                <thead>

                </thead>
                <tbody>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><b>Türü</b></td>
                        <td>
                            @Html.HiddenFor(x => x.PersonelKimlikId)
                            @Html.HiddenFor(x => x.PersonelKursId)
                            @Html.TextBoxFor(x => x.Turu, null, new { @class = "form-control" })
                        </td>
                        <td><b>Şekli</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.Sekli, null, new { @class = "form-control" })
                        </td>
                        <td><b>Konusu</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.Konusu, null, new { @class = "form-control" })
                        </td>
                    </tr>
                    <tr>
                        <td><b>Kurs Sınav Adı</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.KursSinavAdi, null, new { @class = "form-control" })
                        </td>
                        <td><b>Başlangıç Tarihi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.BaslamaTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "Date" })
                        </td>
                        <td><b>Bitiş Tarihi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.BitisTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "Date" })
                        </td>

                    </tr>
            </table>
            <button class="btn btn-warning">Güncelle</button>
        </div>
    </div>
}

WebUI/Views/Course/CourseGetList.cshtml
@using Entities.Concrete
@model List<Course>
@{
    ViewBag.Title = "CourseGetList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Kurs Bilgisi Güncelle</h3>
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title">Kurs Bilgileri</h3>
    </div>
    <div class="box-body">
        <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
            <thead>
                <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">#</th>

                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Türü</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Şekli</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Konusu</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Kurs Sınav Adı</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Başlangıç Tarihi</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Bitiş Tarihi</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var k in Model)
                {
                    <tr role="row" class="odd">
                        <td class="sorting_1"></td>
                        <td>@k.Turu</td>
                        <td>@k.Sekli</td>
                        <td>@k.Konusu</td>
                        <td>@k.KursSinavAdi</td>
                        <td>@k.BaslamaTarihi.ToShortDateString()</td>
                        <td>@k.BitisTarihi.ToShortDateString()</td>
                        <td>
                            <a href="/Course/CourseGet/@k.PersonelKursId" class="btn btn-warning col-xs-pull-5">Güncelle</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
        <br />
        <a href="/Course/CourseAdd/@ViewBag.PersonelKimlikId" class="btn btn-success col-xs-pull-5">Yeni Kurs Bilgisi Ekle</a>
    </div>
</div>

WebUI/Views/Course/CourseQuery.cshtml
@using Entities.Concrete
@model List<Identity>
@{
    ViewBag.Title = "CourseQuery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CourseQuery</h2>

<h2>PersonelKursSorgu</h2>

<h2>GuncelleSorgu</h2>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Personel Ara</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->

    @using (Html.BeginForm("CourseQuery", "Course", FormMethod.Get))
    {

        @Html.TextBox("id")
        <button type="submit" class="btn btn-info col-xs-pull-5">Sorgula</button>
    }

</div>

<!-- /.box-body -->
<div class="box-footer">
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
        <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div>
        <div class="row">
            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">TC Kimlik No</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Adı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Soyadı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Çalıştığı Kurum</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var k in Model)
                        {
                            <tr role="row" class="odd">
                                <td class="sorting_1">@k.TcKimlikNo</td>
                                <td>@k.Adi</td>
                                <td>@k.Soyadi</td>
                                <td>@k.CalistigiKurum</td>
                                <td><a href="/Course/CourseGetList/@k.PersonelKimlikId" class="btn btn-warning col-xs-pull-5">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebUI/Views/Course/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Kurs Bilgisi Güncelle</h3>
<div class="container box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">TC Kimlik No İle Personel Ara</h3><br />
        <br />
        @using (Html.BeginForm("IndexQuery", "Course", FormMethod.Post))
        {
            <div class="row">

                <table>
                    <tr>
                        <td class="col-md-6">@Html.TextBox("TcNo", null, new { @class = "form-control" })</td>
                        <td><button type="submit" class="btn btn-info col-xs-pull-5">Sorgula</button></td>
                    </tr>
                </table>

            </div>

        }
    </div>
</div>

<!-- /.box-body -->
<div class="box-footer">
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
        <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div>
        <div class="row">
            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">TC Kimlik No</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Adı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Soyadı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Çalıştığı Kurum</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                        </tr>
                    </thead>
                    <tbody>


                        <tr role="row" class="odd">
                            <td class="sorting_1"></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebUI/Views/Course/IndexQuery.cshtml
@using Entities.Dto
@model List<PersonDto>
@{
    ViewBag.Title = "IndexQuery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Kurs Bilgisi Güncelle</h3>
<div class="container box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">TC Kimlik No İle Personel Ara</h3><br />
        <br />
        @using (Html.BeginForm("IndexQuery", "Course", FormMethod.Post))
        {
            <div class="row">

                <table>
                    <tr>
                        <td class="col-md-6">@Html.TextBox("TcNo", null, new { @class = "form-control" })</td>
                        <td><button type="submit" class="btn btn-info col-xs-pull-5">Sorgula</button></td>
                    </tr>
                </table>

            </div>

        }
    </div>
</div>
<!-- /.box-body -->
<div class="box-footer">
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
        <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div>
        <div class="row">
            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">#</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">TC Kimlik No</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Adı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Soyadı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Çalıştığı Kurum</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var k in Model)
                        {
                            <tr role="row" class="odd">
                                <td class="sorting_1"></td>
                                <td>@k.TcNo</td>
                                <td>@k.Adi</td>
                                <td>@k.Soyadi</td>
                                <td>@k.CalistigiKurum  @k.IsYeriAdi</td>
                                <td><a href="/Course/CourseGetList/@k.PersonelKimlikId" class="btn btn-warning col-xs-pull-5">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>