WebUI/Controllers/TemporaryDutyController.cs
using Business.Abstract;
using Business.Concrete;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class TemporaryDutyController : Controller
    {

        IIdentityService _ıdentityService;
        ITemporaryDutyService _temporaryDutyService;

        public TemporaryDutyController(IIdentityService ıdentityService, ITemporaryDutyService temporaryDutyService)
        {
            _ıdentityService = ıdentityService;
            _temporaryDutyService = temporaryDutyService;
        }

        // GET: TemporaryDuty
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IndexQuery(string tcNo)
        {
            var result = _ıdentityService.GetPersonDetails(tcNo).Data;
            return View(result);
        }

        public ActionResult TemporaryDutyGetList(int id)
        {

            var temporaryDutyGetList = _temporaryDutyService.GetTemporaryDutyDetails(id).Data;
            return View("TemporaryDutyGetList", temporaryDutyGetList);
        }

        public ActionResult TemporaryDutyGet(int id)
        {
            var temporaryDutyGet = _temporaryDutyService.GetTemporaryDutyDetails(id).Data;

            return View("TemporaryDutyGet", temporaryDutyGet);
        }


        [HttpGet]
        public ActionResult TemporaryDutyUpdate()
        {
            return View();
        }


        [HttpPost]
        public ActionResult TemporaryDutyUpdate(TemporaryDuty temporaryDuty)

        {
            _temporaryDutyService.Update(temporaryDuty);
            return RedirectToAction("");
        }
        [HttpGet]
        public ActionResult TemporaryDutyAdd(int id)
        {
            var temporaryDutyAdd = _temporaryDutyService.GetTemporaryDutyDetails(id).Data;

            return View("TemporaryDutyAdd", temporaryDutyAdd);
        }


        [HttpPost]
        public ActionResult TemporaryDutyAdd(TemporaryDuty temporaryDuty)

        {
            _temporaryDutyService.Add(temporaryDuty);
            return RedirectToAction("");
        }
    }
}

WebUI/Views/TemporaryDuty/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Geçici Görev Bilgisi Güncelle</h3>
<div class="container box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">TC Kimlik No İle Personel Ara</h3><br />
        <br />
        @using (Html.BeginForm("IndexQuery", "TemporaryDuty", FormMethod.Post))
        {
            <div class="row">

                <table>
                    <tr>
                        <td class="col-md-6">@Html.TextBox("TcNo", null, new { @class = "form-control" })</td>
                        <td><button type="submit" class="btn btn-info col-xs-pull-5">Sorgula</button></td>
                    </tr>
                </table>

            </div>

        }
    </div>
</div>

<!-- /.box-body -->
<div class="box-footer">
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
        <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div>
        <div class="row">
            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">TC Kimlik No</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Adı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Soyadı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Çalıştığı Kurum</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr role="row" class="odd">
                            <td class="sorting_1"></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebUI/Views/TemporaryDuty/IndexQuery.cshtml
@using Entities.Dto 
@model List<PersonDto>
@{
    ViewBag.Title = "IndexQuery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Geçici Görev Bilgisi Güncelle</h3>
<div class="container box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">TC Kimlik No İle Personel Ara</h3><br />
        <br />
        @using (Html.BeginForm("IndexQuery", "TemporaryDuty", FormMethod.Post))
        {
            <div class="row">

                <table>
                    <tr>
                        <td class="col-md-6">@Html.TextBox("TcNo", null, new { @class = "form-control" })</td>
                        <td><button type="submit" class="btn btn-info col-xs-pull-5">Sorgula</button></td>
                    </tr>
                </table>

            </div>

        }
    </div>
</div>

<!-- /.box-body -->
<div class="box-footer">
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
        <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div>
        <div class="row">
            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">#</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">TC Kimlik No</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Adı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Soyadı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Çalıştığı Kurum</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var k in Model)
                        {
                            <tr role="row" class="odd">
                                <td class="sorting_1"></td>
                                <td>@k.TcNo</td>
                                <td>@k.Adi</td>
                                <td>@k.Soyadi</td>
                                <td>@k.CalistigiKurum  @k.IsYeriAdi</td>
                                <td><a href="/TemporaryDuty/TemporaryDutyGetList/@k.PersonelKimlikId" class="btn btn-warning col-xs-pull-5">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebUI/Views/TemporaryDuty/TemporaryDutyAdd.cshtml
@using Entities.Concrete
@model TemporaryDuty
@{
    ViewBag.Title = "TemporaryDutyAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Geçici Görev Bilgisi Ekle</h3>
@using (Html.BeginForm("TemporaryDutyAdd", "TemporaryDuty", FormMethod.Post))
{
    <div class="box box-primary">
        <div class="box-header with-border">
            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                <thead>

                </thead>
                <tbody>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><b>Görevlendirildiği Birlik</b></td>
                        <td>
                            @Html.HiddenFor(x => x.PersonelKimlikId)
                            @Html.HiddenFor(x => x.PersonelGeciciGorevId)
                            @Html.TextBoxFor(x => x.GorevlendigiBirlik, null, new { @class = "form-control" })
                        </td>
                        <td><b>Görev Yeri</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.GorevYeri, null, new { @class = "form-control" })
                        </td>

                    </tr>
                    <tr>
                        <td><b>Başlama Tarihi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.BaslamaTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "Date" })
                        </td>
                        <td><b>Bitiş Tarihi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.BitisTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "Date" })
                        </td>

                    </tr>
            </table>
            <button class="btn btn-success">Ekle</button>
        </div>
    </div>
}

WebUI/Views/TemporaryDuty/TemporaryDutyGet.cshtml
@using Entities.Concrete
@model TemporaryDuty

@{
    ViewBag.Title = "TemporaryDutyGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Geçici Görev Bilgisi Güncelle</h3>
@using (Html.BeginForm("TemporaryDutyUpdate", "TemporaryDuty", FormMethod.Post))
{
    <div class="box box-primary">
        <div class="box-header with-border">
            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                <thead>

                </thead>
                <tbody>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><b>Görevlendirildiği Birlik</b></td>
                        <td>
                            @Html.HiddenFor(x => x.PersonelKimlikId)
                            @Html.HiddenFor(x => x.PersonelGeciciGorevId)
                            @Html.TextBoxFor(x => x.GorevlendigiBirlik, null, new { @class = "form-control" })
                        </td>
                        <td><b>Görev Yeri</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.GorevYeri, null, new { @class = "form-control" })
                        </td>

                    </tr>
                    <tr>
                        <td><b>Başlama Tarihi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.BaslamaTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "Date" })
                        </td>
                        <td><b>Bitiş Tarihi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.BitisTarihi,"{0:yyyy-MM-dd}", new { @class = "form-control",@type="Date" })
                        </td>

                    </tr>
            </table>
            <button class="btn btn-warning">Güncelle</button>
        </div>
    </div>
}

WebUI/Views/TemporaryDuty/TemporaryDutyGetList.cshtml
@using Entities.Dto
@model List<TemporaryDutyDto>
@{
    ViewBag.Title = "TemporaryDutyGetList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Geçici Görev Bilgisi Güncelle</h3>


<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title">Geçici Görev Bilgileri</h3>
    </div>
    <div class="box-body">
        <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
            <thead>
                <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending">#</th>

                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Görevlendirildiği Birlik</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Görev Yeri</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Başlama Tarihi</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Bitiş Tarihi</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var e in Model)
                {
                    <tr role="row" class="odd">
                        <td class="sorting_1"></td>
                        <td>@e.IsYeriAdi</td>
                        <td>@e.GorevYeri</td>
                        <td>@e.BaslamaTarihi</td>
                        <td>@e.BitisTarihi</td>

                        <td><a href="/TemporaryDuty/TemporaryDutyGet/@e.PersonelGeciciGorevId" class="btn btn-warning col-xs-pull-5">Güncelle</a></td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>

WebUI/Views/TemporaryDuty/TemporaryDutyQuery.cshtml
@using Entities.Concrete
@model List<Identity>
@{
    ViewBag.Title = "TemporaryDutyQuery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Geçici Görev Bilgisi Güncelle</h3>
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Personel Ara</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->

    @using (Html.BeginForm("TemporaryDutyQuery", "TemporaryDuty", FormMethod.Get))
    {

        @Html.TextBox("id")
        <button type="submit" class="btn btn-info col-xs-pull-5">Sorgula</button>
    }

</div>

<!-- /.box-body -->
<div class="box-footer">
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
        <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div>
        <div class="row">
            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">TC Kimlik No</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Adı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Soyadı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Çalıştığı Kurum</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var k in Model)
                        {
                            <tr role="row" class="odd">
                                <td class="sorting_1">@k.TcKimlikNo</td>
                                <td>@k.Adi</td>
                                <td>@k.Soyadi</td>
                                <td>@k.CalistigiKurum</td>
                                <td><a href="/TemporaryDuty/TemporaryDutyGetList/@k.PersonelKimlikId" class="btn btn-warning col-xs-pull-5">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>