WebUI/Controllers/GraduationController.cs
using Business.Abstract;
using Business.Concrete;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class GraduationController : Controller
    {
        IGraduationService _graduationService;
        IIdentityService _ıdentityService;
        IGraduationStatusService _graduationStatusService;

        public GraduationController(IIdentityService ıdentityService, IGraduationService graduationService, IGraduationStatusService graduationStatusService)
        {
            _ıdentityService = ıdentityService;
            _graduationService = graduationService;
            _graduationStatusService = graduationStatusService;
        }

        // GET: Graduation
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult IndexQuery(string tcNo)
        {
            var result = _ıdentityService.GetPersonDetails(tcNo).Data;
            return View(result);
        }

        public ActionResult GraduationGetList(int id)
        {

            var graduationGetList = _graduationService.GetGraduationDetails(id).Data;
            ViewBag.PersonelKimlikId = id;
            return View("GraduationGetList", graduationGetList);
        }

        public ActionResult GraduationGet(int id)
        {
            var graduationGrp = _graduationStatusService.GetAll().Data;

            ViewBag.GraduationGrpList = new SelectList(graduationGrp,"EgitimDurumId", "EgitimDurumu");

            var graduationGet = _graduationService.GetById(id).Data;

            return View("GraduationGet", graduationGet);
        }


        [HttpGet]
        public ActionResult GraduationUpdate()
        {
            return View();
        }


        [HttpPost]
        public ActionResult GraduationUpdate(Graduation graduation)

        {
            _graduationService.Update(graduation);

            return RedirectToAction("");
        }
        [HttpGet]
        public ActionResult GraduationGetAdd(int id)
        {

            DropBoxItem();
            ViewBag.PersonelKimlikId = id;
            return View();
        }

        [HttpGet]
        public ActionResult GraduationAdd()

        {
            return View();
        }

        [HttpPost]
        public ActionResult GraduationAdd(Graduation graduation)

        {
            _graduationService.Add(graduation);

            return RedirectToAction("");
        }
        private void DropBoxItem()
        {
            var graduationGrp = _graduationStatusService.GetAll().Data;

            ViewBag.GraduationGrpList = new SelectList(graduationGrp, "EgitimDurumId", "EgitimDurumu");
        }
    }
}

WebUI/Views/Graduation/GraduationGet.cshtml
@using Entities.Concrete
@model Graduation
@{
    ViewBag.Title = "GraduationGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Eğitim Bilgisi Güncelle</h3>
@using (Html.BeginForm("GraduationUpdate", "Graduation", FormMethod.Post))
{
    <div class="box box-primary">
        <div class="box-header with-border">
            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                <thead>

                </thead>
                <tbody>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><b>Okul Türü</b></td>
                        <td>
                            @Html.HiddenFor(x => x.PersonelKimlikId)
                            @Html.HiddenFor(x => x.PersonelEgitimId)
                            @Html.TextBoxFor(x => x.OkulTuru, null, new { @class = "form-control" })
                        </td>
                        <td><b>Fakülte / Lise Tür</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.FakulteLiseTur, null, new { @class = "form-control" })
                        </td>
                        <td><b>Tahsil Derecesi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.TahsilDerece, null, new { @class = "form-control" })
                        </td>
                    </tr>
                    <tr>
                        <td><b>Bölüm</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.Bolum, null, new { @class = "form-control" })
                        </td>
                        <td><b>Okul Adı</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.OkulAd, null, new { @class = "form-control" })
                        </td>
                        <td><b>Mezuniyet Durumu</b></td>
                        <td>
                            @Html.DropDownListFor(x => x.EgitimDurumId,ViewBag.GraduationGrpList as SelectList,"----Egitim Durumu---", new { @class = "form-control" })
                        </td>

                    </tr>
            </table>
            <button class="btn btn-warning">Güncelle</button>
        </div>
    </div>
}

WebUI/Views/Graduation/GraduationGetAdd.cshtml
@using Entities.Concrete
@model Graduation
@{
    ViewBag.Title = "GraduationGetAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Eğitim Bilgisi Ekle</h3>
@using (Html.BeginForm("GraduationAdd", "Graduation", FormMethod.Post))
{
    <div class="box box-primary">
        <div class="box-header with-border">
            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                <thead>

                </thead>
                <tbody>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><b>Okul Türü</b></td>
                        <td>
                            @Html.Hidden("PersonelKimlikId", (int)ViewBag.PersonelKimlikId)
                            @Html.HiddenFor(x => x.PersonelEgitimId)
                            @Html.TextBoxFor(x => x.OkulTuru, null, new { @class = "form-control" })
                        </td>
                        <td><b>Fakülte / Lise Tür</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.FakulteLiseTur, null, new { @class = "form-control" })
                        </td>
                        <td><b>Tahsil Derecesi</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.TahsilDerece, null, new { @class = "form-control" })
                        </td>
                    </tr>
                    <tr>
                        <td><b>Bölüm</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.Bolum, null, new { @class = "form-control" })
                        </td>
                        <td><b>Okul Adı</b></td>
                        <td>
                            @Html.TextBoxFor(x => x.OkulAd, null, new { @class = "form-control" })
                        </td>
                        <td><b>Mezuniyet Durumu</b></td>
                        <td>
                            @Html.DropDownListFor(x => x.EgitimDurumId, ViewBag.GraduationGrpList as SelectList,"--- Eğitim Durumu ---", new { @class = "form-control" })
                        </td>

                    </tr>
            </table>
            <button class="btn btn-success">Kaydet</button>
        </div>
    </div>
}

WebUI/Views/Graduation/GraduationGetList.cshtml
@using Entities.Dto
@model List<GraduationDto>
@{
    ViewBag.Title = "GraduationGetList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Eğitim Bilgisi Güncelle</h3>
<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title">Eğitim Bilgileri</h3>
    </div>
    <div class="box-body">
        <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
            <thead>
                <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">#</th>
                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">Okul Türü</th>

                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Fakülte/Lise Tür</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Tahsil Derece</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Bölüm</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Okul Adı</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Mezuniyet Durum</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var e in Model)
                {
                    <tr role="row" class="odd">
                        <td class="sorting_1"></td>
                        <td>@e.OkulTuru</td>
                        <td>@e.FakulteLiseTur</td>
                        <td>@e.TahsilDerece</td>
                        <td>@e.Bolum</td>
                        <td>@e.OkulAd</td>
                        <td>@e.EgitimDurumu</td>
                        <td>
                            <a href="/Graduation/GraduationGet/@e.PersonelEgitimId" class="btn btn-warning col-xs-pull-5">Güncelle</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
        <br />
        <a href="/Graduation/GraduationGetAdd/@ViewBag.PersonelKimlikId" class="btn btn-success col-xs-pull-5">Yeni Eğitim Bilgisi Ekle</a>
    </div>
</div>

WebUI/Views/Graduation/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Eğitim Bilgisi Güncelle</h3>
<div class="container box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">TC Kimlik No İle Personel Ara</h3><br />
        <br />
        @using (Html.BeginForm("IndexQuery", "Graduation", FormMethod.Post))
        {
            <div class="row">

                <table>
                    <tr>
                        <td class="col-md-6">@Html.TextBox("TcNo", null, new { @class = "form-control" })</td>
                        <td><button type="submit" class="btn btn-info col-xs-pull-5">Sorgula</button></td>
                    </tr>
                </table>

            </div>

        }
    </div>
</div>
<!-- /.box-body -->
<div class="box-footer">
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
        <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div>
        <div class="row">
            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">TC Kimlik No</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Adı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Soyadı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Çalıştığı Kurum</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                        </tr>
                    </thead>
                    <tbody>


                        <tr role="row" class="odd">
                            <td class="sorting_1"></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebUI/Views/Graduation/IndexQuery.cshtml
@using Entities.Dto
@model List<PersonDto>
@{
    ViewBag.Title = "IndexQuery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Eğitim Bilgisi Güncelle</h3>
<div class="container box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">TC Kimlik No İle Personel Ara</h3><br />
        <br />
        @using (Html.BeginForm("IndexQuery", "Graduation", FormMethod.Post))
        {
            <div class="row">

                <table>
                    <tr>
                        <td class="col-md-6">@Html.TextBox("TcNo", null, new { @class = "form-control" })</td>
                        <td><button type="submit" class="btn btn-info col-xs-pull-5">Sorgula</button></td>
                    </tr>
                </table>

            </div>

        }
    </div>
</div>

<!-- /.box-body -->
<div class="box-footer">
    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
        <div class="row"><div class="col-sm-6"></div><div class="col-sm-6"></div></div>
        <div class="row">
            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">#</th>
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate " aria-sort="ascending">TC Kimlik No</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Adı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Soyadı</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Çalıştığı Kurum</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Seçim</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var k in Model)
                        {
                            <tr role="row" class="odd">
                                <td class="sorting_1"></td>
                                <td>@k.TcNo</td>
                                <td>@k.Adi</td>
                                <td>@k.Soyadi</td>
                                <td>@k.CalistigiKurum  @k.IsYeriAdi</td>
                                <td><a href="/Graduation/GraduationGetList/@k.PersonelKimlikId" class="btn btn-warning col-xs-pull-5">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>