WebUI/Controllers/WorkingStatusController.cs
using Business.Abstract.Dynamic;
using Entities.Concrete.DynamicDataEntity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class WorkingStatusController : Controller
    {
        IWorkingStatusService _workingStatusService;

        public WorkingStatusController(IWorkingStatusService workingStatusService)
        {
            _workingStatusService = workingStatusService;
        }

        // GET: WorkingStatus
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult WorkingStatusGetAll()
        {
            var result = _workingStatusService.GetAll().Data.ToList();
            return View("WorkingStatusGetAll", result);
        }
        public ActionResult WorkingStatusGetById(int id)
        {
            var result = _workingStatusService.GetById(id).Data;
            return View("WorkingStatusGetById",result);

        }

        [HttpGet]
        public ActionResult WorkingStatusAdd()
        {

            return View();
        }
        [HttpPost]
        public ActionResult WorkingStatusAdd(WorkingStatus workingStatus)
        {
            _workingStatusService.Add(workingStatus);
            return RedirectToAction("WorkingStatusGetAll");
        }

        [HttpGet]
        public ActionResult WorkingStatusUpdate()
        {

            return View();
        }

        [HttpPost]
        public ActionResult WorkingStatusUpdate(WorkingStatus workingStatus)
        {
            _workingStatusService.Update(workingStatus);
            return RedirectToAction("WorkingStatusGetAll");
        }

        [HttpGet]
        public ActionResult WorkingStatusDelete()
        {

            return View();
        }

        [HttpPost]
        public ActionResult WorkingStatusDelete(WorkingStatus workingStatus)
        {
            _workingStatusService.Delete(workingStatus);
            return RedirectToAction("WorkingStatusGetAll");
        }
    }
}

WebUI/Views/WorkingStatus/WorkingStatusAdd.cshtml
@using Entities.Concrete.DynamicDataEntity
@model WorkingStatus
@{
    ViewBag.Title = "WorkingStatusAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>Çalışma Durumu Ekle</h3>
<form method="post">
    <div class="box box-primary">
        <div class="box-header with-border">
            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                <thead>

                </thead>
                <tbody>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><b>Atama Nedeni</b></td>
                        <td>
                            @Html.HiddenFor(x => x.IstihtamDurumId)
                            @Html.TextBoxFor(x => x.IstihtamDurumu, null, new { @class = "form-control" })
                        </td>
                    </tr>
            </table>
            <button class="btn btn-success">Ekle</button>
        </div>
    </div>
</form>

WebUI/Views/WorkingStatus/WorkingStatusGetAll.cshtml
@using Entities.Concrete.DynamicDataEntity
@model List<WorkingStatus>
@{
    ViewBag.Title = "WorkingStatusGetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box box-info">
    <div class="box-header">
        <h3 class="box-title">Çalışma Durumu</h3>
    </div>
    <div class="box-body">
        <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
            <thead>
                <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending">#</th>
                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1">Çalışma Durumu</th>

                    <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">İşlem</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var e in Model)
                {
                    <tr role="row" class="odd">
                        <td class="sorting_1">@e.IstihtamDurumId</td>
                        <td>@e.IstihtamDurumu</td>
                        <td>
                            <a href="/WorkingStatus/WorkingStatusGetById/@e.IstihtamDurumId" class="btn btn-warning col-xs-pull-5">Güncelle</a>
                            <a href="/WorkingStatus/WorkingStatusDelete/@e.IstihtamDurumId" class="btn btn-danger col-xs-pull-5">Sil</a>
                        </td>

                    </tr>
                }
                <tr role="row" class="odd">
                    <td colspan="2"></td>
                    <td>
                        <a href="/WorkingStatus/WorkingStatusAdd" class="btn btn-success col-xs-pull-5" style="width:128px">Yeni Ekle</a>
                    </td>
                </tr>
            </tbody>
        </table>

    </div>
    <!-- /.box-body -->
</div>

WebUI/Views/WorkingStatus/WorkingStatusGetById.cshtml
@using Entities.Concrete.DynamicDataEntity
@model WorkingStatus
@{
    ViewBag.Title = "WorkingStatusGetById";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Çalışma Durumu Güncelle</h3>
@using (Html.BeginForm("WorkingStatusUpdate", "WorkingStatus", FormMethod.Post))
{
    <div class="box box-primary">
        <div class="box-header with-border">
            <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                <thead>

                </thead>
                <tbody>
                    <tr role="row" class="odd">
                        <td class="sorting_1"><b>Çalışma Durumu</b></td>
                        <td>
                            @Html.HiddenFor(x => x.IstihtamDurumId)
                            @Html.TextBoxFor(x => x.IstihtamDurumu, null, new { @class = "form-control" })
                        </td>
                    </tr>
            </table>
            <button class="btn btn-warning">Güncelle</button>
        </div>
    </div>
}